project:
  type: website

website:
  title: "Lola Hertsenberg"

  navbar:
    title: "Lola Hertsenberg"
    background: "#FFFDF8"
    foreground: "#13294B"
    pinned: true

    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: work.qmd
        text: Work
      - href: experience.qmd
        text: Experience
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true